import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import Container from "@/components/Container";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body>
        <Header />
        <main className="pt-[var(--navigation-height)] bg-page-gradient">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
